
CREATE TABLE book (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255),
                      author VARCHAR(255)
);

CREATE TABLE review (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        comment VARCHAR(255),
                        rating INT,
                        book_id BIGINT,
                        FOREIGN KEY (book_id) REFERENCES book(id)
);

INSERT INTO book (id, title, author) VALUES (1, 'Book Title 1', 'Author 261');
INSERT INTO book (id, title, author) VALUES (2, 'Book Title 2', 'Author 148');
INSERT INTO book (id, title, author) VALUES (3, 'Book Title 3', 'Author 7');
INSERT INTO book (id, title, author) VALUES (4, 'Book Title 4', 'Author 117');
INSERT INTO book (id, title, author) VALUES (5, 'Book Title 5', 'Author 153');
INSERT INTO book (id, title, author) VALUES (6, 'Book Title 6', 'Author 186');
INSERT INTO book (id, title, author) VALUES (7, 'Book Title 7', 'Author 18');
INSERT INTO book (id, title, author) VALUES (8, 'Book Title 8', 'Author 39');
INSERT INTO book (id, title, author) VALUES (9, 'Book Title 9', 'Author 29');
INSERT INTO book (id, title, author) VALUES (10, 'Book Title 10', 'Author 104');
INSERT INTO book (id, title, author) VALUES (11, 'Book Title 11', 'Author 260');
INSERT INTO book (id, title, author) VALUES (12, 'Book Title 12', 'Author 26');
INSERT INTO book (id, title, author) VALUES (13, 'Book Title 13', 'Author 1');
INSERT INTO book (id, title, author) VALUES (14, 'Book Title 14', 'Author 42');
INSERT INTO book (id, title, author) VALUES (15, 'Book Title 15', 'Author 243');
INSERT INTO book (id, title, author) VALUES (16, 'Book Title 16', 'Author 41');
INSERT INTO book (id, title, author) VALUES (17, 'Book Title 17', 'Author 250');
INSERT INTO book (id, title, author) VALUES (18, 'Book Title 18', 'Author 129');
INSERT INTO book (id, title, author) VALUES (19, 'Book Title 19', 'Author 120');
INSERT INTO book (id, title, author) VALUES (20, 'Book Title 20', 'Author 260');
INSERT INTO book (id, title, author) VALUES (21, 'Book Title 21', 'Author 260');
INSERT INTO book (id, title, author) VALUES (22, 'Book Title 22', 'Author 192');
INSERT INTO book (id, title, author) VALUES (23, 'Book Title 23', 'Author 17');
INSERT INTO book (id, title, author) VALUES (24, 'Book Title 24', 'Author 83');
INSERT INTO book (id, title, author) VALUES (25, 'Book Title 25', 'Author 93');
INSERT INTO book (id, title, author) VALUES (26, 'Book Title 26', 'Author 46');
INSERT INTO book (id, title, author) VALUES (27, 'Book Title 27', 'Author 296');
INSERT INTO book (id, title, author) VALUES (28, 'Book Title 28', 'Author 58');
INSERT INTO book (id, title, author) VALUES (29, 'Book Title 29', 'Author 255');
INSERT INTO book (id, title, author) VALUES (30, 'Book Title 30', 'Author 247');
INSERT INTO book (id, title, author) VALUES (31, 'Book Title 31', 'Author 178');
INSERT INTO book (id, title, author) VALUES (32, 'Book Title 32', 'Author 172');
INSERT INTO book (id, title, author) VALUES (33, 'Book Title 33', 'Author 19');
INSERT INTO book (id, title, author) VALUES (34, 'Book Title 34', 'Author 7');
INSERT INTO book (id, title, author) VALUES (35, 'Book Title 35', 'Author 244');
INSERT INTO book (id, title, author) VALUES (36, 'Book Title 36', 'Author 130');
INSERT INTO book (id, title, author) VALUES (37, 'Book Title 37', 'Author 205');
INSERT INTO book (id, title, author) VALUES (38, 'Book Title 38', 'Author 118');
INSERT INTO book (id, title, author) VALUES (39, 'Book Title 39', 'Author 85');
INSERT INTO book (id, title, author) VALUES (40, 'Book Title 40', 'Author 265');
INSERT INTO book (id, title, author) VALUES (41, 'Book Title 41', 'Author 271');
INSERT INTO book (id, title, author) VALUES (42, 'Book Title 42', 'Author 180');
INSERT INTO review (id, comment, rating, book_id) VALUES (1, 'Review comment 1', 4, 1);
INSERT INTO review (id, comment, rating, book_id) VALUES (2, 'Review comment 2', 2, 1);
INSERT INTO review (id, comment, rating, book_id) VALUES (3, 'Review comment 3', 4, 2);
INSERT INTO review (id, comment, rating, book_id) VALUES (4, 'Review comment 4', 2, 2);
INSERT INTO review (id, comment, rating, book_id) VALUES (5, 'Review comment 5', 4, 3);
INSERT INTO review (id, comment, rating, book_id) VALUES (6, 'Review comment 6', 2, 3);
INSERT INTO review (id, comment, rating, book_id) VALUES (7, 'Review comment 7', 4, 4);
INSERT INTO review (id, comment, rating, book_id) VALUES (8, 'Review comment 8', 5, 4);
INSERT INTO review (id, comment, rating, book_id) VALUES (9, 'Review comment 9', 4, 5);
INSERT INTO review (id, comment, rating, book_id) VALUES (10, 'Review comment 10', 2, 5);
INSERT INTO review (id, comment, rating, book_id) VALUES (11, 'Review comment 11', 3, 6);
INSERT INTO review (id, comment, rating, book_id) VALUES (12, 'Review comment 12', 1, 6);
INSERT INTO review (id, comment, rating, book_id) VALUES (13, 'Review comment 13', 5, 7);
INSERT INTO review (id, comment, rating, book_id) VALUES (14, 'Review comment 14', 2, 7);
INSERT INTO review (id, comment, rating, book_id) VALUES (15, 'Review comment 15', 3, 8);
INSERT INTO review (id, comment, rating, book_id) VALUES (16, 'Review comment 16', 1, 8);
INSERT INTO review (id, comment, rating, book_id) VALUES (17, 'Review comment 17', 3, 9);
INSERT INTO review (id, comment, rating, book_id) VALUES (18, 'Review comment 18', 1, 9);
INSERT INTO review (id, comment, rating, book_id) VALUES (19, 'Review comment 19', 1, 10);
INSERT INTO review (id, comment, rating, book_id) VALUES (20, 'Review comment 20', 4, 10);
INSERT INTO review (id, comment, rating, book_id) VALUES (21, 'Review comment 21', 2, 11);
INSERT INTO review (id, comment, rating, book_id) VALUES (22, 'Review comment 22', 2, 11);
INSERT INTO review (id, comment, rating, book_id) VALUES (23, 'Review comment 23', 1, 12);
INSERT INTO review (id, comment, rating, book_id) VALUES (24, 'Review comment 24', 2, 12);
INSERT INTO review (id, comment, rating, book_id) VALUES (25, 'Review comment 25', 1, 13);
INSERT INTO review (id, comment, rating, book_id) VALUES (26, 'Review comment 26', 5, 13);
INSERT INTO review (id, comment, rating, book_id) VALUES (27, 'Review comment 27', 4, 14);
INSERT INTO review (id, comment, rating, book_id) VALUES (28, 'Review comment 28', 2, 14);
INSERT INTO review (id, comment, rating, book_id) VALUES (29, 'Review comment 29', 5, 15);
INSERT INTO review (id, comment, rating, book_id) VALUES (30, 'Review comment 30', 1, 15);
INSERT INTO review (id, comment, rating, book_id) VALUES (31, 'Review comment 31', 4, 16);
INSERT INTO review (id, comment, rating, book_id) VALUES (32, 'Review comment 32', 5, 16);
INSERT INTO review (id, comment, rating, book_id) VALUES (33, 'Review comment 33', 4, 17);
INSERT INTO review (id, comment, rating, book_id) VALUES (34, 'Review comment 34', 5, 17);
INSERT INTO review (id, comment, rating, book_id) VALUES (35, 'Review comment 35', 5, 18);
INSERT INTO review (id, comment, rating, book_id) VALUES (36, 'Review comment 36', 1, 18);
INSERT INTO review (id, comment, rating, book_id) VALUES (37, 'Review comment 37', 4, 19);
INSERT INTO review (id, comment, rating, book_id) VALUES (38, 'Review comment 38', 5, 19);
INSERT INTO review (id, comment, rating, book_id) VALUES (39, 'Review comment 39', 5, 20);
INSERT INTO review (id, comment, rating, book_id) VALUES (40, 'Review comment 40', 5, 20);
INSERT INTO review (id, comment, rating, book_id) VALUES (41, 'Review comment 41', 3, 21);
INSERT INTO review (id, comment, rating, book_id) VALUES (42, 'Review comment 42', 4, 21);
INSERT INTO review (id, comment, rating, book_id) VALUES (43, 'Review comment 43', 4, 22);
INSERT INTO review (id, comment, rating, book_id) VALUES (44, 'Review comment 44', 3, 22);
INSERT INTO review (id, comment, rating, book_id) VALUES (45, 'Review comment 45', 2, 23);
INSERT INTO review (id, comment, rating, book_id) VALUES (46, 'Review comment 46', 1, 23);
INSERT INTO review (id, comment, rating, book_id) VALUES (47, 'Review comment 47', 4, 24);
INSERT INTO review (id, comment, rating, book_id) VALUES (48, 'Review comment 48', 3, 24);
INSERT INTO review (id, comment, rating, book_id) VALUES (49, 'Review comment 49', 4, 25);
INSERT INTO review (id, comment, rating, book_id) VALUES (50, 'Review comment 50', 2, 25);
INSERT INTO review (id, comment, rating, book_id) VALUES (51, 'Review comment 51', 4, 26);
INSERT INTO review (id, comment, rating, book_id) VALUES (52, 'Review comment 52', 2, 26);
INSERT INTO review (id, comment, rating, book_id) VALUES (53, 'Review comment 53', 5, 27);
INSERT INTO review (id, comment, rating, book_id) VALUES (54, 'Review comment 54', 4, 27);
INSERT INTO review (id, comment, rating, book_id) VALUES (55, 'Review comment 55', 2, 28);
INSERT INTO review (id, comment, rating, book_id) VALUES (56, 'Review comment 56', 5, 28);
INSERT INTO review (id, comment, rating, book_id) VALUES (57, 'Review comment 57', 3, 29);
INSERT INTO review (id, comment, rating, book_id) VALUES (58, 'Review comment 58', 5, 29);
INSERT INTO review (id, comment, rating, book_id) VALUES (59, 'Review comment 59', 2, 30);
INSERT INTO review (id, comment, rating, book_id) VALUES (60, 'Review comment 60', 2, 30);
INSERT INTO review (id, comment, rating, book_id) VALUES (61, 'Review comment 61', 5, 31);
INSERT INTO review (id, comment, rating, book_id) VALUES (62, 'Review comment 62', 5, 31);
INSERT INTO review (id, comment, rating, book_id) VALUES (63, 'Review comment 63', 1, 32);
INSERT INTO review (id, comment, rating, book_id) VALUES (64, 'Review comment 64', 5, 32);
INSERT INTO review (id, comment, rating, book_id) VALUES (65, 'Review comment 65', 2, 33);
INSERT INTO review (id, comment, rating, book_id) VALUES (66, 'Review comment 66', 1, 33);
INSERT INTO review (id, comment, rating, book_id) VALUES (67, 'Review comment 67', 5, 34);
INSERT INTO review (id, comment, rating, book_id) VALUES (68, 'Review comment 68', 2, 34);
INSERT INTO review (id, comment, rating, book_id) VALUES (69, 'Review comment 69', 2, 35);
INSERT INTO review (id, comment, rating, book_id) VALUES (70, 'Review comment 70', 5, 35);
INSERT INTO review (id, comment, rating, book_id) VALUES (71, 'Review comment 71', 5, 36);
INSERT INTO review (id, comment, rating, book_id) VALUES (72, 'Review comment 72', 1, 36);
INSERT INTO review (id, comment, rating, book_id) VALUES (73, 'Review comment 73', 5, 37);
INSERT INTO review (id, comment, rating, book_id) VALUES (74, 'Review comment 74', 5, 37);
INSERT INTO review (id, comment, rating, book_id) VALUES (75, 'Review comment 75', 2, 38);
INSERT INTO review (id, comment, rating, book_id) VALUES (76, 'Review comment 76', 4, 38);
INSERT INTO review (id, comment, rating, book_id) VALUES (77, 'Review comment 77', 5, 39);
INSERT INTO review (id, comment, rating, book_id) VALUES (78, 'Review comment 78', 2, 39);